@startuml
!include https://raw.githubusercontent.com/cccg8105/UCB-service/master/docs/diagrams/styles.puml
title Diagrama de componentes

interface "HTTP" as http

package "Backend" {
    database Persistencia
    [Servicio] - http
    [Servicio] -down-> Persistencia
    [Servicio] -left-> [UCB]

}

package "Frontend" {
    [Web] -> http
}

@enduml
