@startjson
#highlight "option" / "int" / "0" / "0"
#highlight "option" / "int" / "1" / "1"
#highlight "option" / "int" / "2" / "2"

{
    "option": { "int": [{"0": "Anuncio A"},{"1": "Anuncio B"},{"2": "Anuncio C"}]},
    "reward": { "int": [{"0": "Cerró anuncio"},{"1": "Ingresó al anuncio"}]}
}


@endjson
