@startuml styles
skinparam usecase {
  backgroundColor skyblue
  BorderColor skyblue
  BackgroundColor<< Correct >> lightgreen
  BorderColor<< Correct >> lightgreen
  ArrowColor black
  ActorBorderColor black
  ActorFontName Courier
  BackgroundColor<< Error >> Antiquewhite
  BorderColor<< Error >> Antiquewhite
}
skinparam sequence {
  LifeLineBorderColor Green
  ArrowColor black
  ParticipantBorderColor black
  ParticipantBackgroundColor GreenYellow
  ParticipantFontColor black
}
skinparam actor {
  backgroundColor white
  borderColor slategray
}

skinparam entity {
  backgroundColor white
  borderColor slategray
}

skinparam state {
  StartColor green
  EndColor Red
  BackgroundColor white
  BackgroundColor<<Warning>> Olive
  BorderColor black
  ArrowColor Olive
  BarColor green
}
skinparam activity {
  StartColor green
  BarColor black
  EndColor red
  BackgroundColor white
  DiamondBackgroundColor white
  DiamondBorderColor red
  BorderColor black
  ArrowColor black
}
skinparam cloud {
  borderColor lightgray
  backgroundColor white
}
skinparam node {
  borderColor black
  backgroundColor Yellow
}
skinparam interface {
  borderColor black
  backgroundColor lime
}
skinparam component {
  borderColor slategray
  backgroundColor white
}
skinparam file {
  borderColor black
  backgroundColor white
}
skinparam queue {
  borderColor black
  backgroundColor springgreen
}
skinparam database {
  borderColor slategray
  backgroundColor white
}
skinparam agent {
  borderColor black
  backgroundColor white
}
skinparam rectangle {
  borderColor black
  backgroundColor white
}
skinparam card {
  borderColor black
  backgroundColor white
}
skinparam note {
  borderColor black
  backgroundColor lightCyan
}
skinparam title {
  FontSize 18
}

skinparam class {
  BackgroundColor white
  ArrowColor black
  BorderColor black
}

skinparam boundary {
  BackgroundColor white
  ArrowColor black
  BorderColor slategray
}

skinparam control {
  BackgroundColor white
  ArrowColor black
  BorderColor slategray
}

skinparam package {
  borderColor slategray
  'backgroundColor<<register>> LightSkyBlue
}
@enduml
